version: '3.8'
services:
  app:
    image: openjdk:22
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./consumer/target:/app
      - ./service/target:/app
      - ./provider/target:/app